QUE 1: . Explain the difference between a Python list and a NumPy array in terms of 
memory usage and performance. 
Then, write a program that creates both and performs element-wise 
multiplication.

ANS:-  MEMORY USAGES

🔹 Python List:
Each element is an object. It stores a pointer to that object → more memory consumption.

🔹 NumPy Array:
Stores data in a continuous block of memory → less memory usage and faster access.

PERFORMANCE

🔹 Python List:
Needs explicit loops for operations → slower for large datasets.

🔹 NumPy Array:
Uses vectorized operations implemented in C → much faster.

In [1]:
import numpy as np

# Python List
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

result_list = [a * b for a, b in zip(list1, list2)]
print("List Multiplication:", result_list)

# NumPy Array
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

result_array = array1 * array2
print("NumPy Multiplication:", result_array)


List Multiplication: [6, 14, 24, 36, 50]
NumPy Multiplication: [ 6 14 24 36 50]


QUE 2: What is broadcasting in NumPy? 
Create a 3×3 NumPy array and add a 1D array to it using broadcasting. Explain 
how NumPy applies the operation internally.  

ANS :-  Broadcasting in NumPy means performing arithmetic operations on arrays of different shapes without explicitly reshaping them.

# NumPy automatically expands the smaller array to match the shape of the larger array.

Broadcasting Rules:-

Dimensions are compared from right to left.

Two dimensions are compatible if:

They are equal, OR

One of them is 1.

If compatible, NumPy virtually stretches (repeats) the smaller array.

In [2]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([10,20,30])

print(A + B)   # Broadcasting


[[11 22 33]
 [14 25 36]
 [17 28 39]]


QUE 3:  What are missing values in Pandas and how are they represented? 
Create a DataFrame with missing values and write code to: 
• Detect missing values 
• Replace them with the column mean 
Explain each step. 

ANS :-  Missing Values in Pandas (Assignment Answer)

Missing values are the data entries that are not available or undefined in a dataset.

Representation in Pandas:

1.NaN (Not a Number) → Used for missing values in numeric columns

2.None → Used in object (string) type columns

3.NaT (Not a Time) → Used for missing values in date/time columns

In [3]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Marks': [85, 90, np.nan],
    'Name': ['Aman', None, 'Riya']
})

print(df)


   Marks  Name
0   85.0  Aman
1   90.0   NaN
2    NaN  Riya


QUE 4:  4. Explain boolean indexing in NumPy or Pandas. 
Create a DataFrame with at least 5 columns and filter rows based on two conditions 
using logical operators. Explain how filtering works internally. 

ANS :-    Boolean indexing is a method used to filter data based on conditions.
It uses True/False (Boolean values) to select rows that satisfy a condition.

When a condition is applied:

Pandas creates a Boolean mask (a series of True/False values).

Rows with True are selected.

Rows with False are ignored.

LOGICAL OPERATORS:- AND 

In [1]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Karan', 'Neha', 'Rahul'],
    'Math': [85, 92, 76, 88, 95],
    'Science': [78, 89, 85, 91, 72],
    'Age': [18, 19, 18, 20, 19]
})

# Boolean filtering with two conditions
result = df[(df['Math'] > 80) & (df['Age'] == 19)]

print(result)


    Name  Math  Science  Age
1   Riya    92       89   19
4  Rahul    95       72   19


QUE 5:  . What is the purpose of the groupby() function in Pandas? 
Create a DataFrame with categorical data (e.g., department & salary) and calculate 
the average salary per department using groupby(). Explain the output. 


ANS:-   The groupby() function is used to group data based on one or more columns and then apply aggregate functions like:

1.mean()

2.sum()

3.count()

4.max()

5.min()

EXPLAIN THE OUTPUT:-
Step 1: Grouping

df.groupby('Department')

Groups rows based on department names (HR, IT, Finance).

Step 2: Selecting Salary Column

['Salary']

Selects salary values for each group.

Step 3: Applying Mean

.mean()

Calculates the average salary for each department.

OUTPUT:-

Explanation:

HR → (30000 + 35000) / 2 = 32500

IT → (50000 + 60000) / 2 = 55000

Finance → (40000 + 45000) / 2 = 42500

In [2]:
import pandas as pd

df = pd.DataFrame({
    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance', 'Finance'],
    'Salary': [30000, 50000, 35000, 60000, 40000, 45000]
})

print(df.groupby('Department')['Salary'].mean())


Department
Finance    42500.0
HR         32500.0
IT         55000.0
Name: Salary, dtype: float64
